# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 27) do

  create_table "comment_assoc", :force => true do |t|
    t.column "parent_id", :integer, :default => 0, :null => false
    t.column "child_id",  :integer, :default => 0, :null => false
  end

  create_table "comments", :force => true do |t|
    t.column "user_id",    :integer,  :default => 0, :null => false
    t.column "entry_id",   :integer
    t.column "comment_id", :integer
    t.column "subject",    :string
    t.column "comment",    :text,                    :null => false
    t.column "parent_id",  :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "elizees", :force => true do |t|
    t.column "photo_id",     :integer
    t.column "file",         :string,   :null => false
    t.column "width",        :integer,  :null => false
    t.column "height",       :integer,  :null => false
    t.column "width_web",    :integer,  :null => false
    t.column "height_web",   :integer,  :null => false
    t.column "width_thumb",  :integer,  :null => false
    t.column "height_thumb", :integer,  :null => false
    t.column "user_id",      :integer,  :null => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "entries", :force => true do |t|
    t.column "user_id",    :integer,  :default => 0, :null => false
    t.column "mood_id",    :integer
    t.column "music",      :string
    t.column "subject",    :string
    t.column "entry",      :text,                    :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "entries_topics", :id => false, :force => true do |t|
    t.column "entry_id", :integer, :default => 0, :null => false
    t.column "topic_id", :integer, :default => 0, :null => false
  end

  create_table "haikus", :force => true do |t|
    t.column "user_id",    :integer,                     :null => false
    t.column "haiku",      :text,                        :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "good_flag",  :boolean,  :default => false
  end

  create_table "lepers", :force => true do |t|
    t.column "name", :string
  end

  create_table "moods", :force => true do |t|
    t.column "mood", :string, :default => "", :null => false
  end

  create_table "oblique_strategies", :force => true do |t|
    t.column "oblique_strategy", :string, :default => "", :null => false
  end

  create_table "photoalbums", :force => true do |t|
    t.column "user_id",    :integer,  :null => false
    t.column "parent_id",  :integer
    t.column "name",       :string,   :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "photos", :force => true do |t|
    t.column "user_id",       :integer,  :null => false
    t.column "title",         :string
    t.column "description",   :text
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "photoalbum_id", :integer,  :null => false
    t.column "elizee_id",     :integer
    t.column "position",      :integer,  :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "signup_codes", :force => true do |t|
    t.column "code",  :string, :default => "", :null => false
    t.column "email", :string, :default => "", :null => false
  end

  create_table "topics", :force => true do |t|
    t.column "topic", :string, :default => "", :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login",      :string
    t.column "password",   :string
    t.column "name",       :string
    t.column "email",      :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "last_login", :datetime
    t.column "admin_flag", :integer,  :default => 0, :null => false
  end

end
